# Generated by Django 4.2.4 on 2023-08-18 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_remove_solicitudes_fecha_respuesta_reporte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(default=None, upload_to='adjuntos/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='solicitudes',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='adjuntos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.adjuntos'),
        ),
    ]
