# Generated by Django 4.2.4 on 2023-08-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_adjuntos_alter_solicitudes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudes',
            options={'verbose_name': 'Solicitudes', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='adjuntos',
            field=models.FileField(null=True, upload_to='adjuntos/'),
        ),
        migrations.DeleteModel(
            name='Adjuntos',
        ),
    ]
