# Generated by Django 4.2.4 on 2023-08-21 21:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_rename_contenido_respuestas_respuesta_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjuntos',
            name='archivo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='adjuntos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='respuesta_servidor',
            field=models.CharField(default='Escriba la respuesta a la solicitud', max_length=500, verbose_name='Contenido de la respuesta del servidor público'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='adjuntos',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='solicitudes.adjuntos'),
            preserve_default=False,
        ),
    ]
