# Generated by Django 4.2.4 on 2023-08-22 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_alter_adjuntos_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjuntos',
            name='archivo',
            field=models.FileField(null=True, upload_to='adjuntos/'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='adjuntos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.adjuntos'),
        ),
    ]
