# Generated by Django 4.2.4 on 2023-08-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_alter_adjuntos_archivo_alter_solicitudes_adjuntos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestas',
            options={'verbose_name': 'Respuestas', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterModelOptions(
            name='solicitudes',
            options={'verbose_name': 'Solicitudes', 'verbose_name_plural': 'Solicitudes'},
        ),
    ]
