# Generated by Django 4.2.4 on 2023-08-24 20:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_alter_respuestas_options_alter_solicitudes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contraseña', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuario',
            },
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='fecha_respuesta',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de respuesta'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='descripcion',
            field=models.CharField(default='Describa la solicitud a enviar', max_length=500),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_reporte',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Fecha del reporte'),
        ),
    ]
